// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using docker_sandbox_dev_api.Dal;

namespace docker_sandbox_dev_api.Migrations
{
    [DbContext(typeof(SandboxDbContext))]
    [Migration("20191119092133_modify-model")]
    partial class modifymodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("docker_sandbox_dev_api.Dal.Model.Sandbox", b =>
                {
                    b.Property<Guid>("SandboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DockerContainerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DockerContainerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DockerContainerPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SandboxCreationConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SandboxId");

                    b.HasIndex("UserId");

                    b.ToTable("Sandboxes");
                });

            modelBuilder.Entity("docker_sandbox_dev_api.Dal.Model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("docker_sandbox_dev_api.Dal.Model.Sandbox", b =>
                {
                    b.HasOne("docker_sandbox_dev_api.Dal.Model.User", "User")
                        .WithMany("Sandboxes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
